all:
  children:
    haproxy:
      hosts:
        proxy_host:
          ansible_host: 3.109.184.13
    inference:
      hosts:
        inference_host:
          ansible_host: 10.0.2.152
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q -i ../infra/sparklehood-dev-key.pem ubuntu@3.109.184.13"'